---
forumone::databases: 
  {{db_name}}: 
    username: {{db_user}}

forumone::webserver::vhosts:  
  vagrant: 
    path: "/vagrant/{{app_webroot}}"

{{#solr}}
forumone::solr::collections:  
  drupal: 
    order: 1
{{/solr}}